apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: deployment-test1
  labels: 
    app: backend
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: backend
  template: 
    metadata:
      labels: 
        app: backend 
    spec:
      containers:
      - name: backend
        image: nginx
        ports:
          - containerPort: 80