apiVersion: v1 
kind: Service
metadata:
  name: my-service1
  labels:
    app: backend
spec:
  type: NodePort
  selector: 
    app: backend
  ports:
    - protocol: TCP
      port: 8080 
      targetPort: 80
      nodePort: 30007