apiVersion: apps/v1 
kind: Deployment 
metadata:
  annotations:
    kubernetes.io/change-cause: "Error, fake"
  name: deployment-test
  labels:
    app: front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: nginx
        image: nginx:testfake #error forzado
        ports:
        - containerPort: 110 