apiVersion: v1 
kind: Pod 
metadata:
  name: podtest3
  labels:
    app: front #autodefinible (podemos poner lo que deseemos, app es la más empleada)
    env: dev
spec:
  containers:
      - name: cont1
        image: nginx:alpine
---
apiVersion: v1 
kind: Pod 
metadata:
  name: podtest4
  labels: 
    app: backend
    env: dev
spec:
  containers:
      - name: cont1
        image: nginx:alpine
