apiVersion: v1 #kubectl api-versions (empleamos la última). No tiene prefijo (correspondiente a api-group, se ven en kubectl api-resources)
kind: Pod #kubectl api-resources | grep Pod (para seleccionar la denominación correcta de tipo)
metadata:
  name: podtest2
spec:
  containers:
      - name: cont1
        image: nginx:alpine
        #command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600'] #posible sobreescribir el cmd del contenedor
