apiVersion: v1 
kind: Pod 
metadata:
  name: podtest3
spec:
  containers:
      - name: cont1
        image: nginx:alpine
---
apiVersion: v1 
kind: Pod 
metadata:
  name: podtest4
spec:
  containers:
      - name: cont1
        image: nginx:alpine
